version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: restaurants
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  app:
#    build: .
#    container_name: best-matched-restaurants-app
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurants
#      SPRING_DATASOURCE_USERNAME: usuario
#      SPRING_DATASOURCE_PASSWORD: senha123
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#    restart: always

volumes:
  pgdata: