spring:
  application:
    name: best-matched-restaurants-mfp

  datasource:
    url: jdbc:h2:file:./data/restaurants
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# spring.jpa.show-sql: true  # descomentando ativa logs SQL

springdoc:
  packages-to-scan: com.mailson.pereira.tech.assessment.web
  swagger-ui:
    path: /swagger-ui.html
  api:
    title: "Application for tech assessment"